language: ruby
cache: bundler
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.1

env:
 - PUPPET_VERSION=3.7.3

script: 'bundle exec rake tests'

notifications:
  email:
    on_failure: change
    on_success: never
